import{a as c,S as d,i as l}from"./assets/vendor-CNqCr-V-.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();c.defaults.baseURL="https://pixabay.com/api/";const f="54261320-d62ab16d38fae836d0ed4fba4";function m(s){return c.get("",{params:{key:f,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0}})}const n=document.querySelector(".gallery");document.querySelector(".loader");const y=new d(".gallery a");function p(s){const o=s.map(r=>`
    <li>
      <a href="${r.largeImageURL}">
        <img src="${r.webformatURL}" alt="${r.tags}" loading="lazy"/>
      </a>
      <p>Likes: ${r.likes} | Views: ${r.views} | Comments: ${r.comments} | Downloads: ${r.downloads}</p>
    </li>
  `).join("");n.insertAdjacentHTML("beforeend",o),y.refresh()}function g(){n.innerHTML=""}function h(){n.classList.add("loading")}function L(){n.classList.remove("loading")}const u=document.querySelector(".form"),b=u.querySelector("input[name='search-text']");u.addEventListener("submit",async s=>{s.preventDefault();const o=b.value.trim();if(!o){l.warning({title:"Warning",message:"Please enter a search term!"});return}g(),h();try{const a=(await m(o)).data.hits;a.length===0?l.info({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!"}):p(a)}catch(r){console.error(r),l.error({title:"Error",message:"Something went wrong. Please try again later!"})}finally{L()}});
//# sourceMappingURL=index.js.map
